spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/economiafam
    username: economiafam
    password: economiafam
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: "DSAFGJOSDGJBDVNSORUGHE57649THG938G5H9H9539H84HE8GH9WERW0HJFI4HF98E4GHE98H"
    issuer: "economia-familiare"
    accessTokenMinutes: 1
    refreshTokenDays: 7

app:
  cors:
    allowed-origins: "http://localhost:5173"
  security:
    refresh-cookie-name: "refresh_token"
    refresh-cookie-path: "/auth"
    refresh-cookie-days: 7
    cookie-secure: false
    cookie-samesite: Lax
  dev:
    artificial-delay-ms: 1500

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE